#!/usr/bin/env python

Import('env')
Import("env_modules")
#print("Hello from Zoom SCsub")

env_zoom = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []
# 
thirdparty_dir = "#thirdparty/zoom/"
# thirdparty_bin_dir = thirdparty_dir + "bin/"
thirdparty_h_dir = thirdparty_dir + "h/"
thirdparty_lib_dir = thirdparty_dir + "lib/"
# #thirdparty_sources = Glob(".dll")
# #print(thirdparty_sources)
# 
env_zoom.Prepend(CPPPATH=[thirdparty_h_dir])
env.Append(LIBPATH=[thirdparty_lib_dir])
env.Append(LIBS=["sdk.windows.tools.64.lib"])
# 
# env_thirdparty = env_zoom.Clone()
# env_thirdparty.disable_warnings()
# #env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
# env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []
env.add_source_files(env.modules_sources, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)

